// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCUqz13c-jVLk17Ui04ivVCOu9Rh0vvA',
    appId: '1:851360982939:web:e679a0b89b4f32d48a233e',
    messagingSenderId: '851360982939',
    projectId: 'fitnessapp-aede3',
    authDomain: 'fitnessapp-aede3.firebaseapp.com',
    storageBucket: 'fitnessapp-aede3.appspot.com',
    measurementId: 'G-2HRBC6G6WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxliTe4L-471iq7levuVrfu_ajp8XTM3s',
    appId: '1:851360982939:android:098954dfacd15c368a233e',
    messagingSenderId: '851360982939',
    projectId: 'fitnessapp-aede3',
    storageBucket: 'fitnessapp-aede3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Xz39EZylnObrMNhAU5NkJmVUk_EKq44',
    appId: '1:851360982939:ios:864a74652a942a548a233e',
    messagingSenderId: '851360982939',
    projectId: 'fitnessapp-aede3',
    storageBucket: 'fitnessapp-aede3.appspot.com',
    iosBundleId: 'com.example.fitnesstrackingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Xz39EZylnObrMNhAU5NkJmVUk_EKq44',
    appId: '1:851360982939:ios:864a74652a942a548a233e',
    messagingSenderId: '851360982939',
    projectId: 'fitnessapp-aede3',
    storageBucket: 'fitnessapp-aede3.appspot.com',
    iosBundleId: 'com.example.fitnesstrackingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzCUqz13c-jVLk17Ui04ivVCOu9Rh0vvA',
    appId: '1:851360982939:web:5ac1b85747969cf58a233e',
    messagingSenderId: '851360982939',
    projectId: 'fitnessapp-aede3',
    authDomain: 'fitnessapp-aede3.firebaseapp.com',
    storageBucket: 'fitnessapp-aede3.appspot.com',
    measurementId: 'G-SNSV3CT0DF',
  );

}